export {};
/**
 * Imports completed/missed status from the HTML training plan analysis.
 * Reads _plan_status.json (generated by extracting HTML colors) and
 * updates matching planned workouts in the database.
 *
 * Run: SEED_EMAIL=uppfinnarnoa@gmail.com npx tsx scripts/import-plan-status.ts
 */
import * as fs from "fs";
import * as path from "path";
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

function isoWeekMonday(weekNum: number, year: number): Date {
  const jan4 = new Date(year, 0, 4);
  const dayOfWeek = jan4.getDay() || 7;
  const week1Monday = new Date(jan4);
  week1Monday.setDate(jan4.getDate() - (dayOfWeek - 1));
  const result = new Date(week1Monday);
  result.setDate(week1Monday.getDate() + (weekNum - 1) * 7);
  return result;
}

function toDateStr(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}

interface DayStatus { name: string; status: string | null; }
interface WeekData  { week: number; days: DayStatus[]; }

async function main() {
  const email = process.env.SEED_EMAIL ?? "admin@traininglab.local";
  const user = await prisma.user.findUnique({ where: { email } });
  if (!user) { console.error(`User ${email} not found.`); process.exit(1); }

  const jsonPath = path.join(process.cwd(), "scripts", "_plan_status.json");
  const weeks: WeekData[] = JSON.parse(fs.readFileSync(jsonPath, "utf-8"));

  let updated = 0, skipped = 0, notFound = 0;
  let crossedWeek52 = false;

  for (const wk of weeks) {
    const year = (wk.week >= 43 && !crossedWeek52) ? 2025 : 2026;
    if (wk.week === 52) crossedWeek52 = true;

    const monday = isoWeekMonday(wk.week, year);

    for (let d = 0; d < 7; d++) {
      const day = wk.days[d];
      if (!day?.name || !day.status || day.status === "race") continue;
      // race/quality/moderate are type hints, not status — skip them
      if (!["completed", "missed"].includes(day.status)) { skipped++; continue; }

      const dateObj = new Date(monday);
      dateObj.setDate(monday.getDate() + d);
      const dateStr = toDateStr(dateObj);

      // Find the matching planned workout by date + fuzzy name match
      const workoutsOnDay = await prisma.plannedWorkout.findMany({
        where: { userId: user.id, date: new Date(dateStr) },
      });

      if (workoutsOnDay.length === 0) { notFound++; continue; }

      // Match by name similarity (case-insensitive contains)
      const planName = day.name.toLowerCase().trim();
      const match = workoutsOnDay.find((w: { name: string }) =>
        w.name.toLowerCase().includes(planName.slice(0, 6)) ||
        planName.includes(w.name.toLowerCase().slice(0, 6))
      ) ?? workoutsOnDay[0]; // fallback: first workout of that day

      if (match.status !== "planned") { skipped++; continue; } // already logged, don't overwrite

      await prisma.plannedWorkout.update({
        where: { id: match.id },
        data: {
          status:    day.status,
          markedAt:  new Date(),
          // For missed workouts: check if the reason was Sjukdom (VECKA 10 = sick)
          missedReason: day.status === "missed" ? "other" : null,
        },
      });
      updated++;
    }
  }

  console.log(`✓ Updated: ${updated} | Skipped (already logged): ${skipped} | Not found: ${notFound}`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
